arr="""FOMIN,SAQIF,6
PAPERNO,XINNI,12
WILLIAMS,SKAI,14
GINDIS,MOZEN,11
MORSE,ANDREA,17
LOW,ARIEL,12
ZAMAN,ALEXANDRIA,12
HUMAIDEE,AFIA,19
SHAN,NATALIA,5
SHAHID,EDWARD,5
TEDESCO,CARINA,14
HLINKA,ZAMIN,9
STACY,JIA,9
SHIN,JIAYI,11
ZHAN,MALIKA,10
LETON,HEPZIBAH,14
KUCHINAD,VIANA,12
LEUSSING,REGINA,8
CHEN,EBTESHAM,17
AUDHY,ELAINE,10
WIELAARD,ANI,8
MARUF,VIOLETA,15
CUNNINGHAM,TANISHA,6
TAMEEM,AQIB,17
BISTA,ANGELA,4
KHALIQUE,RAMEZ,12
LOU,CYRUS,17
PERAZZO,KRIPAMOYE,3
FRID,JOSEPH,17
HAQUE,ANNE,9
FANTOZZI,ALVI,7
LANDA,ISABELLE,8
VALLEJO,VICKY,13
XHETANI,ZAINAB,8
LAKUSTA,MANVEER,12
FIROOZAN,OLIVIER,9
KARIM,SOPHIA,6
SCHWARZ,ESTEAK,10
KROP-SIEGMUND,TAASEEN,12
MUI,YE-HEE,16
SHAPIRO,MIM,13
GUTKOVICH,JAY,11
CHIU,HUMAIRA,17
BAHUTSKI,KAIDEN,11
FUKUOKA,RIFAH,10
CASTLE,SHAFKATH,3
VAYSBURD,KAZI,10
ANDREWS,MICHA,10
CAOTHIEN,DREW,10
RABINOVICH,DANIEL,8
OR,LUCINDA,16
KABWA,WEIBIN,6
MEDINA,SAKURA,17
ANANT,TERREN,13
RUZZIER,GITAE,13
SY,IQRA,11
PULAWSKA,ROXY,13
REN,YUVAL,12
BACCHUS,OLUWATOBI,9
JEA,FLORENCE,11
BAE,IRENE,13
HUGHES,LEON,16
COWAN,INARA,10
SHEN,KEN,16
ILYANOK,CHENHUI,8
COLLINS,SELENA,10
MIKHALEVSKY,MADELYN,12
MAI,NAFISA,4
GRAEBER,SAYAN,20
BOIS,ALIND,8
TSAHALIS,MANOLEE,6
GALAI,QINA,13
ROHAN,ALFAYED,7
KRONMAN,MORRIS,9
KYI,GRETA,11
TAWHID,INFINITY,4
KRANICH,WAI,4
KOLENOVIC,DORIN,3
LEUNG,XINQING,18
BELL,SAARAH,14
TYLO,MISA,16
TASNEEM,DAVALYNN,7
AZIZ,MELODY,16
SOIEFER,KANJUDA,17
FUENTES,MENDY,2
SAI,CALISTA,10
BACON,ANIKAH,17
ALLEN,KHUJISTA,16
JIA,KEIRA,5
LEVINE,TAMARA,10
EISEN,PULINDU,10
ASHIKIN,FATIHA,3
LAMANY,AIDEN,6
SCHWARTZ,ATHENA,6
RUSSO,FARIHAH,17
KATARI,SUBYETA,16
ZOARDAR,MISHEL,17
HAMEED,YVETTE,15
HARVEY,CALVIN,10
SELECTOR,DANTE,6"""


def strtolistSort(S):
    L = S.split("\n")
    print (L)
    firstnames = []
    lastnames = []
    tests = []
    longfirst = ""
    longlast = ""
    for i in range(len(L)):
        L[i] = L[i].split(",")
    ###
    print (L)
    ###
    for i in range(len(L)):
        firstnames += [L[i][1]]
        if ([i+1] != len(firstnames)) and (len(firstnames[i]) < len(firstnames[i+1])):
            longfirst = firstnames[i+1]
            
    ###
    print (firstnames, longfirst)
    ###
    
    
        
    
    

print(strtolistSort(arr))
    
    